---
- name: Ensure HTTP for apt is installed
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  become: yes

- name: Import MS apt key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  become: yes

- name: Add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic main"
    filename: "dotnetdev"
    state: present
    update_cache: yes
  become: yes

- name: Install dotnet core
  apt:
    name: "dotnet-sdk-2.1"
    state: present
    update_cache: yes
  become: yes
