---
- hosts: all

  vars:
    applications:
      - thunar
      - vlc
      - docker
      - docker-compose
      - htop
      - vagrant
      - virtualbox
      - winff
      - youtube-dl
      - zathura
    
  tasks:
    - name: Ensure Up-to-date system
      apt:
        update_cache: yes
        upgrade: safe
      become: yes

    - name: Ensure Application are installed
      apt:
          name: "{{item}}"
          state: latest
      with_items: "{{applications}}"
      become: yes

    - name: Ensure Code dir exists
      file:
        path: ~/Code
        state: directory
      become: no

    - name: Ensure Notes dir exists
      file:
        path: ~/Notes
        state: directory
      become: no

    - name: Ensure Pictures/Wallpapers dir exists
      file:
        path: ~/Pictures/Wallpapers
        state: directory
      become: no

    - name: Ensure git installation and configuration
      include: reusable/git.yml

    - name: Ensure rust installation and configuration
      include: reusable/rust.yml

    - name: Ensure golang installation and configuration
      include: reusable/golang.yml

    - name: Ensure xmonad installation and configuration
      include: reusable/xmonad.yml

    - name: Ensure oh-my-zsh setup
      include: reusable/ohmyzsh.yml

    - name: Ensure neovim installation and configuration
      include: reusable/neovim.yml

    - name: Ensure vivaldi installation
      include: reusable/vivaldi.yml

